export const ERROR_CODES = {
    VALIDATION: {
        REQUIRED: "REQUIRED",
        TOO_SHORT: "TOO_SHORT",
        TOO_LONG: "TOO_LONG",
        INVALID_FORMAT: "INVALID_FORMAT",
        INVALID_EMAIL: "INVALID_EMAIL",
        MISSING_UPPERCASE: "MISSING_UPPERCASE",
        MISSING_LOWERCASE: "MISSING_LOWERCASE",
        MISSING_NUMBER: "MISSING_NUMBER",
        HAS_LEADING_OR_TRAILING_SPACES: "HAS_LEADING_OR_TRAILING_SPACES",
    },
    AUTH: {
        INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
        INVALID_TOKEN: "INVALID_TOKEN",
        TOKEN_EXPIRED: "TOKEN_EXPIRED",
        INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
        UNAUTHORIZED: "UNAUTHORIZED",
    },
    AUTHORIZATION: {
        FORBIDDEN: "FORBIDDEN",
    },
    RESOURCE: {
        USER_NOT_FOUND: "USER_NOT_FOUND",
        EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
        STORE_NOT_FOUND: "STORE_NOT_FOUND",
    },
    FILE: {
        FILE_TOO_LARGE: "FILE_TOO_LARGE",
        INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
        FILE_REQUIRED: "FILE_REQUIRED",
    },
    SYSTEM: {
        INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    },
} as const;
