version: "3.8"

services:
    postgres_db:
        image: postgres:16-alpine # Usamos la versión 16 (puedes cambiarla) en su versión ligera 'alpine'
        container_name: node_prisma_postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres_password}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT:-5432}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data:
        driver: local
